name: tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Run rustfmt
        id: rustfmt
        run: |
          cargo fmt --all -- --check || exit 1

      - name: Annotate with reviewdog
        if: failure()
        uses: reviewdog/action-suggester@v1
        with:
          tool: rustfmt
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: warning

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Run tests async
        run: cargo test --features async -- async
      - name: Run example sync_minimal
        run: cargo run --example sync_minimal
      - name: Run example sync_polling
        run: cargo run --example sync_polling
      - name: Run example async_await
        run: cargo run --example async_await --features async
      - name: Run example full_example
        run: cargo run --example full_example
      - name: Run bench
        run: cargo bench
      - name: Run bench async
        run: cargo bench --features async
